// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SSST.Data;

namespace SSST.Migrations
{
    [DbContext(typeof(SSSTContext))]
    [Migration("20200701174101_newKey")]
    partial class newKey
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SSST.Models.Guru", b =>
                {
                    b.Property<int>("GuruID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GuruNama")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GuruID");

                    b.ToTable("Guru");
                });

            modelBuilder.Entity("SSST.Models.Kelas", b =>
                {
                    b.Property<int>("KelasID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GuruID")
                        .HasColumnType("int");

                    b.Property<string>("KelasNama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KelasTahun")
                        .HasColumnType("int");

                    b.HasKey("KelasID");

                    b.HasIndex("GuruID");

                    b.ToTable("Kelas");
                });

            modelBuilder.Entity("SSST.Models.MataPelajaran", b =>
                {
                    b.Property<int>("MapelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GuruID")
                        .HasColumnType("int");

                    b.Property<int>("KelasID")
                        .HasColumnType("int");

                    b.Property<string>("MapelDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MapelGrade")
                        .HasColumnType("int");

                    b.Property<string>("MapelNama")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MapelID");

                    b.HasIndex("GuruID");

                    b.HasIndex("KelasID");

                    b.ToTable("MataPelajaran");
                });

            modelBuilder.Entity("SSST.Models.Siswa", b =>
                {
                    b.Property<int>("SiswaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("KelasID")
                        .HasColumnType("int");

                    b.Property<string>("SiswaAlamat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiswaNama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiswaNim")
                        .HasColumnType("nvarchar(12)")
                        .HasMaxLength(12);

                    b.HasKey("SiswaID");

                    b.HasIndex("KelasID");

                    b.ToTable("Siswa");
                });

            modelBuilder.Entity("SSST.Models.SiswaNilai", b =>
                {
                    b.Property<int>("SiswaID")
                        .HasColumnType("int");

                    b.Property<int>("MapelID")
                        .HasColumnType("int");

                    b.Property<float>("Nilai")
                        .HasColumnType("real");

                    b.HasKey("SiswaID", "MapelID");

                    b.HasIndex("MapelID");

                    b.ToTable("SiswaNilai");
                });

            modelBuilder.Entity("SSST.Models.Kelas", b =>
                {
                    b.HasOne("SSST.Models.Guru", "Guru")
                        .WithMany()
                        .HasForeignKey("GuruID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SSST.Models.MataPelajaran", b =>
                {
                    b.HasOne("SSST.Models.Guru", "Guru")
                        .WithMany()
                        .HasForeignKey("GuruID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SSST.Models.Kelas", "Kelas")
                        .WithMany("Mapels")
                        .HasForeignKey("KelasID")
                        .IsRequired();
                });

            modelBuilder.Entity("SSST.Models.Siswa", b =>
                {
                    b.HasOne("SSST.Models.Kelas", "Kelas")
                        .WithMany("Siswas")
                        .HasForeignKey("KelasID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SSST.Models.SiswaNilai", b =>
                {
                    b.HasOne("SSST.Models.MataPelajaran", "MataPelajaran")
                        .WithMany("SiswaNilais")
                        .HasForeignKey("MapelID");

                    b.HasOne("SSST.Models.Siswa", "Siswa")
                        .WithMany("SiswaNilais")
                        .HasForeignKey("SiswaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
